### ISSUE TITLE
Binding files are ignored unless they have the .jxb file extension

### ISSUE THREAD

**Issue by spaligo** [mojohaus/jaxb2-maven-plugin#59] opened 2016-10-04 22:24 UTC
Binding files are ignored unless they have the .jxb file extension. For example, the following does nothing:

&lt;xjbSource&gt;${basedir}/src/main/resources/xjb/my-bindings.xml&lt;/xjbSource&gt;

**Comment by lennartj** [comment] 2016-10-06 04:50
What happens if you remove the ${basedir} from xjbSource element?

**Comment by spaligo** [comment] 2016-10-06 15:59
Same problem.

**Comment by lennartj** [comment] 2018-05-13 12:09
This is actually working as intended. Will fix documentation to indicate the algorithm here.
Unless you explicitly give a value to xjbExcludes, standard excludes will be in effect.
For XJB sources, the standard excludes are files ending in `xsd` plus any of the following file endings:

```java
private static final String[] STANDARD_EXCLUDE_SUFFIXES = {"README.*", "\\.xml", "\\.txt"};
```

**Closed** 2018-05-13 12:10 UTC
Labels: documentation, wontfix
