### ISSUE TITLE
Running 'mvn install' without doing a clean first causes build to not find previously generated sources.

### ISSUE THREAD

**Issue by PredatorVI** [mojohaus/jaxb2-maven-plugin#35] opened 2015-10-07 20:21 UTC
We recently tried upgrading from v1.5 to 2.2 of the plugin and noticed that if we do 'mvn clean install' the build works every time, but if we do 'mvn clean install' followed by 'mvn install' or 'mvn compile', the project fails to resolve class files that were generated as part of the previous run of the plugin.

My best guess is that it only includes the generated sources directory in the build classpath if the plugin actually generates files, otherwise it omits it.

Version 1.5 of the plugin does not exhibit this behavior, but 2.1 and 2.2 both do.

**Comment by Black-Drag0n** [comment] 2015-10-12 19:35
We are experiencing the same problem

**Comment by lennartj** [comment] 2015-10-12 20:16
True; this will be patched in 2.3.
Seems a straightforward enough thing to do.

**Comment by lennartj** [comment] 2016-05-26 19:30
This report is a duplicate of #44.

**Closed by lennartj** 2016-05-26 19:30 UTC
Labels: duplicate
