### ISSUE TITLE
<sources> parameter for schemagen is ignored!

### ISSUE THREAD

**Issue by rankinc** [mojohaus/jaxb2-maven-plugin#10] opened 2015-07-12 10:53 UTC
Consider a trivial Maven project with POM:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>testing</groupId>
    <artifactId>test-jaxb</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>Test JAXB</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <version>2.1</version>
                <configuration>
                    <sources>
                        <source>src/main/java/org/testing/xml</source>
                    </sources>
                    <transformSchemas>
                        <transformSchema>
                            <uri>example</uri>
                            <toPrefix>ex</toPrefix>
                            <toFile>example.xsd</toFile>
                        </transformSchema>
                    </transformSchemas>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>schemagen</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```
And the following source files:
```
package org.testing;

public class TestJaxb {

    private final String label;

    public TestJaxb(String label) {
        this.label = label;
    }

    public String getLabel() {
        return label;
    }

    public static void main(String[] arg) {
        System.out.println("I am not an XML file");
    }

}
```
```
package org.testing.xml;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class MyType {

    private String name;

    @XmlElement(required = true)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
```
And `package-info.java`
```
@XmlSchema(
    namespace = "example",
    elementFormDefault = XmlNsForm.QUALIFIED
)
package org.testing.xml;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
```
This project fails to compile because `org.testing.TestJaxb` is passed to schemagen, *despite not belonging to the `org.testing.xml` package, as required by the `<sources>` configuration*!

**Comment by lennartj** [comment] 2015-07-12 12:01
The problem here is the ClassCastException as indicated by your log.
This ClassCastException is a duplicate of #7

**Comment by rankinc** [comment] 2015-07-12 12:31
**THE PROBLEM IS NOT THE `ClassCastException`!**.  **EVEN IF THE EXCEPTION WERE NOT THROWN, THE PLUGIN WOULD STILL BE PASSING `org.testing.TestJaxb` TO SCHEMAGEN, CONTRARY TO THE `<sources>` CONFIGURATION!!!!**

**Closed** 2015-07-12 14:01 UTC
