### ISSUE TITLE
SCHEMAGEN - JAVADOC - XML TYPE

### ISSUE THREAD

**Issue by simfol59** [mojohaus/jaxb2-maven-plugin#38] opened 2015-11-10 12:57 UTC
In the version of the maven plugin 2.2 of jaxb2-maven-plugin with the goal "schemagen" and "createJavaDocAnnotations" attribute set to true, if a Java Class is annotated with @XmlType having a name different from the Java Class Name, then the XSD schema generated doesn't have the xs:documentation tag for the xs:complexType related to the Java Class.

**Comment by lennartj** [comment] 2015-11-11 11:02
Duplicate of #25

**Closed by lennartj** 2015-11-11 11:02 UTC
Labels: duplicate
