### ISSUE TITLE
<sources> parameter for schemagen is ignored!

### ISSUE THREAD

**Issue by rankinc** [mojohaus/jaxb2-maven-plugin#11] opened 2015-07-12 12:45 UTC
The trival Maven project below generates an extra and completely bogus `schema2.xsd` artifact
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0">

  <xs:complexType name="testJaxb">
    <xs:annotation>
      <xs:documentation/>
    </xs:annotation>
    <xs:sequence/>
  </xs:complexType>
</xs:schema>
```
**This artifact should not be generated because the `org.testing.TestJaxb` class is explicitly excluded by the plugin's configuration**:

    <sources>
        <source>src/main/java/org/testing/xml</source>
    </source>

Passing non-JAXB classes to `schemagen` is likely to throw exceptions - which is hardly surprising really.
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>testing</groupId>
    <artifactId>test-jaxb</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>Test JAXB</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
    </properties>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
            </plugin>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <version>2.1</version>
                <configuration>
                    <sources>
                        <source>src/main/java/org/testing/xml</source>
                    </sources>
                    <transformSchemas>
                        <transformSchema>
                            <uri>example</uri>
                            <toPrefix>ex</toPrefix>
                            <toFile>example.xsd</toFile>
                        </transformSchema>
                    </transformSchemas>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>schemagen</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```
And the following source files:
```
package org.testing;

public class TestJaxb {

    public static void main(String[] arg) {
        System.out.println("I am not an XML file");
    }

}
```
```
package org.testing.xml;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

@XmlRootElement
public class MyType {

    private String name;

    @XmlElement(required = true)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
```
And `package-info.java`
```
@XmlSchema(
    namespace = "example",
    elementFormDefault = XmlNsForm.QUALIFIED
)
package org.testing.xml;

import javax.xml.bind.annotation.XmlNsForm;
import javax.xml.bind.annotation.XmlSchema;
```

**Comment by lennartj** [comment] 2015-07-12 14:02
Duplicate of #3

**Closed** 2015-07-12 14:01 UTC
